services:

  backend:
    image: 500782030335.dkr.ecr.ap-south-1.amazonaws.com/student-backend:latest

    container_name: student_backend

    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: 5000
      NODE_ENV: production

    ports:
      - "5000:5000"

    restart: unless-stopped

    networks:
      - student_network

  frontend:
    image: 500782030335.dkr.ecr.ap-south-1.amazonaws.com/student-frontend:latest

    container_name: student_frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: unless-stopped

    networks:
      - student_network

networks:
  student_network: