name: Deploy Application

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::500782030335:role/github-actions-role
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Get Terraform Outputs
        id: tf
        run: |
          echo "EC2_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV
          echo "BACKEND_ECR=$(terraform output -raw backend_ecr_url)" >> $GITHUB_ENV
          echo "FRONTEND_ECR=$(terraform output -raw frontend_ecr_url)" >> $GITHUB_ENV
          echo "RDS_ENDPOINT=$(terraform output -raw rds_endpoint)" >> $GITHUB_ENV
          echo "DB_USERNAME=$(terraform output -raw db_username)" >> $GITHUB_ENV
          echo "DB_PASSWORD=$(terraform output -raw db_password)" >> $GITHUB_ENV

      - name: Login To ECR
        run: |
          aws ecr get-login-password \
          --region ap-south-1 | docker login \
          --username AWS \
          --password-stdin 500782030335.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Backend Image
        run: |
          docker build \
          -t $BACKEND_ECR:latest \
          ../backend

      - name: Build Frontend Image
        run: |
          docker build \
          -t $FRONTEND_ECR:latest \
          ../frontend

      - name: Push Backend Image
        run: docker push $BACKEND_ECR:latest

      - name: Push Frontend Image
        run: docker push $FRONTEND_ECR:latest

      - name: Create Compose File
        run: |
          cat > docker-compose.yml <<EOF
          services:

            backend:
              image: $BACKEND_ECR:latest
              container_name: student_backend

              environment:
                DB_HOST: $RDS_ENDPOINT
                DB_USER: $DB_USERNAME
                DB_PASSWORD: $DB_PASSWORD
                DB_NAME: student_registration
                PORT: 5000

              ports:
                - "5000:5000"

              restart: always

            frontend:
              image: $FRONTEND_ECR:latest
              container_name: student_frontend

              ports:
                - "80:80"

              depends_on:
                - backend

              restart: always
          EOF

      - name: Save SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > student-key-new.pem
          chmod 400 student-key-new.pem

      - name: Copy Compose To EC2
        run: |
          scp \
          -o StrictHostKeyChecking=no \
          -i student-key-new.pem \
          docker-compose.yml \
          ubuntu@$EC2_IP:/home/ubuntu/docker-compose.yml

      - name: Deploy On EC2
        run: |
          ssh \
          -o StrictHostKeyChecking=no \
          -i student-key-new.pem \
          ubuntu@$EC2_IP << EOF

          aws ecr get-login-password \
          --region ap-south-1 | docker login \
          --username AWS \
          --password-stdin 500782030335.dkr.ecr.ap-south-1.amazonaws.com

          docker compose -f docker-compose.yml pull

          docker compose -f docker-compose.yml down || true

          docker compose -f docker-compose.yml up -d

          EOF